const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#FF69B4",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#0D0D0D",
    cardForeground: "#FFFFFF",
    primary: "#FF69B4",
    primaryForeground: "#000000",
    secondary: "#1A1A1A",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A1A",
    mutedForeground: "#888888",
    accent: "#FF69B4",
    accentForeground: "#000000",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#FF69B4",
    input: "#1A1A1A",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF69B4",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#0D0D0D",
    cardForeground: "#FFFFFF",
    primary: "#FF69B4",
    primaryForeground: "#000000",
    secondary: "#1A1A1A",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A1A",
    mutedForeground: "#888888",
    accent: "#FF69B4",
    accentForeground: "#000000",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#FF69B4",
    input: "#1A1A1A",
  },
  radius: 12,
};

export default colors;
